# Generated by Django 2.2.16 on 2022-07-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220717_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_author_group',
        ),
    ]
